### ISSUE TITLE
Create an appclient protocol for EE application client tests

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-jakarta#4]
We need a new protocol and test execution implementation for running application client based tests like those used in the EE TCK.

**Comment by jamezp** [comment]
I was actually thinking about this last week because I've been looking at some issues with WildFly Arquillian and it's custom JMX Protocol. 

I do wonder if the JMX protocol would be okay for this. It's somewhat standard.

**Comment by scottmarlow** [comment]
JMX is no longer in Jakarta EE so not really something we could require Jakarta EE implementations to implement.

**Comment by starksm64** [comment]
I have a prototype that is actually going to be outside of the arquillian
codebase because its behavior is specific to how the Jakarta TCK expects
the console output to be formatted. This version remove the need to have a
managed container know anything about whether it is running an appclient.

**Comment by starksm64** [comment]
So the appclient protocol is very Jakarta EE CTS specific, so I don't think a general version will work. Closing this issue.
