### ISSUE TITLE
Update the arquillian-core dependency to 1.9.0.Final

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-jakarta#8]
The arquillian-core 1.9.0.Final release fixed some Junit5 behavior, and updated its bom to only include the artifacts in the arquillian-core release. Currently the dependency on arquillian-core 1.7.1.Final is inconsistent dependency because that arquillian-core bom includes a different arquillian-jakarta release.

**Comment by hantsy** [comment]
Waiting it available in Maven central repository, https://repo.maven.apache.org/maven2/org/jboss/arquillian/jakarta/arquillian-jakarta-bom/

**Comment by jamezp** [comment]
> Waiting it available in Maven central repository, https://repo.maven.apache.org/maven2/org/jboss/arquillian/jakarta/arquillian-jakarta-bom/

I'm not following what you're waiting for @hantsy. arquillian-jakarta has a [BOM for 1.8.1.Final](https://repo.maven.apache.org/maven2/org/jboss/arquillian/jakarta/arquillian-jakarta-bom/1.8.1.Final/), it won't have one anytime soon for 1.9.0.Final as it's a separate project and has a different release cycle.

**Comment by hantsy** [comment]
@jamezp As provided in this related PR, it should have a `10.0.0.Final` to align with aruqillian core `1.9.0.Final`.

**Comment by starksm64** [comment]
It is there as of now:
![arq-jakarta-bom](https://github.com/arquillian/arquillian-jakarta/assets/332210/1c205d77-e204-463a-8ed7-485af6d87d37)
